# Generated by Django 6.0.2 on 2026-02-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_status'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('doctor', 'date', 'start_time', 'end_time')},
        ),
    ]
